[build]
xargo = false
default-target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
dockerfile = "dockerfiles/Dockerfile.x86_64"

[target.aarch64-unknown-linux-gnu]
dockerfile = "dockerfiles/Dockerfile.aarch64"