FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

RUN apt-get update && apt-get install --assume-yes clang zlib1g-dev libelf-dev
RUN dpkg --add-architecture arm64
RUN apt-get update && apt-get install --assume-yes zlib1g-dev:arm64 libelf-dev:arm64
