name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # Trigger the workflow on push to tags like v1.0, v20.15.10
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang libelf-dev zlib1g-dev

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust artifacts
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}

    - name: Format
      run: cargo fmt --all -- --check

    - name: Test
      run: cargo test

    - name: Clippy
      run: cargo clippy --all --tests --all-features --no-deps

    - name: Build
      if: github.event_name != 'pull_request'
      run: cargo build --release

    - name: Rename binary
      if: github.event_name != 'pull_request'
      run: mv target/release/bpftop target/release/bpftop-${{ matrix.target }}

    - name: Upload artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v7
      with:
        name: bpftop-${{ matrix.target }}
        path: target/release/bpftop-${{ matrix.target }}
        if-no-files-found: error

  create_release:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      id: download_artifacts
      uses: actions/download-artifact@v8
      with:
        pattern: bpftop-*
        path: artifacts
        merge-multiple: true

    - name: Create Release and Upload Artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: artifacts/bpftop-*
        draft: true
        allowUpdates: true
        updateOnlyUnreleased: true
